version: '3.4'
services:
  spark:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-network
    volumes:
      - './data:/data'
  spark-worker:
    build:
      context: ./worker
    depends_on:
      - spark
    environment:
      - "SPARK_MASTER=spark://spark:7077"
    networks:
      - spark-network
    volumes:
      - './data:/data'
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - spark-network
networks:
  spark-network:
    driver: bridge
